### PR TITLE
remove use of g_error()

### LINKED ISSUE #221: Usage of `g_error` in source code causes core dumps
transmission-daemon-4.0.2-1.fc37.x86_64
transmission-remote-gtk-1.5.1-2.fc37.x86_64

Prerequisites:

1. Transmission daemon is up and running, and have some active torrents (probably, completed). 
2. Transmission daemon is running using "transmission" user account.
3. Files in /var/lib/transmission/.config/transmission-daemon/torrents belongs to "transmission" user and not accessible by other users.

Looks like it is standard linux layout.

Steps to reproduce the crash:

1. Run transmission-remote-gtk (I suppose the user does not use "transmission" account).
2. Press Ctrl+O, "Add a Torrent" dialog is shown.
3. Navigate to /var/lib/transmission/.config/transmission-daemon/torrents and select any file, press "Add" button.

Voilà. transmission-remote-gtk crashed. In the terminal:

    $ transmission-remote-gtk 
    ** (transmission-remote-gtk:15132): ERROR **: 01:35:23.063: Failed to open file “/var/lib/transmission/.config/transmission-daemon/torrents/0abc88b24de1a941754bff6f04d8fe8661f4dbe5.torrent”: open() failed: Permission denied
    Trace/breakpoint trap (core dumped)

It is not a big problem, but transmission-remote-gtk should not crash if it can't open a torrent file anyway.

### PR DESCRIPTION
**Pull request by LaserEyess**
Fixes #221

### CODE REVIEW

**Comment by LaserEyess** [comment]
@van-de-bugger please try this to make sure it fixes it for you. It should pop up an error dialog if there's a permissions issue. The error message is not the best, but it's what glib returns.

File: src/util.c [hunk 1]
```diff
@@ -180,15 +180,13 @@ gboolean is_url(const gchar *string)
...
-    GError *error = NULL;
-    GMappedFile *mf = g_mapped_file_new(filename, FALSE, &error);
+    GMappedFile *mf = g_mapped_file_new(filename, FALSE, error);
     gchar *b64out = NULL;
 
-    if (error) {
-        g_error("%s", error->message);
-        g_error_free(error);
+    if (error && *error) {
+        return NULL;
```
Comment (TingPing) [inline src/util.c:189]: This can be in a bad state if `error == NULL && `mf == NULL`.

I would probably just put a `g_assert(error != NULL)` before it is used. This is an internal API and we should always be passing an error.

Comment (TingPing) [reply src/util.c:189]: This same comment applies to src/trg-file-parser.c

File: src/trg-prefs.c [hunk 2]
```diff
@@ -419,7 +420,7 @@ gboolean trg_prefs_save(TrgPrefs *p)
     g_free(dirName);
 
     if (!success) {
-        g_error("Problem creating parent directory (permissions?) for: %s\n", priv->file);
+        g_warning("Problem creating parent directory (permissions?) for: %s\n", priv->file);
```
Comment (TingPing) [inline src/trg-prefs.c:423]:
```suggestion
        g_warning("Problem creating parent directory (permissions?) for: %s", priv->file);
```

File: src/util.c (hunk 1 above)
Comment (LaserEyess) [reply src/util.c:189]: I'm confused how that state could ever happen. I assume `error` can never be `NULL` but I added the check just because it seems weird to dereference it without an explicit check.

**Comment by van-de-bugger** [comment]
> @van-de-bugger please try this to make sure it fixes it for you. It should pop up an error dialog if there's a permissions issue. The error message is not the best, but it's what glib returns.

I am not familiar with git and git hub. I have managed to checkout the `mater` branch, but I have no idea how to checkout your changes.

**Comment by LaserEyess** [comment]
You can get a patch file by appending `.patch' to the URL: https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/222.patch

But also, I can just create one for you: https://0x0.st/H8j3.patch

**Comment by van-de-bugger** [comment]
Hi, sorry for delay.

Ok, with the patch TRG does not crash but shows a dialog box with decent error message. 

There are few problems, though: 

1. When error box is closed, TRG continues as if the torrent file was successfully open and shows "Add torrent" dialog with *empty* file list. Since torrent file was not read, there is no any sense to show this dialog.
2. If I am trying to open more than one unreadable torrent files, the error box is **not** shown at all (something flickers on the screen, but my eye is not so fast to see what it is there), but "Add torrent" dialog is still shown.

**Comment by LaserEyess** [comment]
Can you open an issue for each of those separately?
